### ISSUE TITLE
Anchors aren't preserved when Dhall expressions are evaluated

### ISSUE THREAD

**Issue by robbiemcmichael** [robbiemcmichael/dhaml#3]
Current behaviour:

```bash
$ cat anchors.yaml
```
```yaml
anchor: &anchor !dhall |
  [1, 2]
list: *anchor
```

```bash
$ dhaml anchors.yaml
```
```yaml
anchor:
- 1
- 2
list: *anchor
```

----

Expected behaviour:

```bash
$ dhaml anchors.yaml
```
```yaml
anchor: &anchor
- 1
- 2
list: *anchor
```
